spring:
    profiles:
        active:
            - dev
---
server:
    port: 1111
spring:
    profiles: dev
    application:
        name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://192.168.141.1:7002/eureka/
  instance:
    instance-id: microservicecloud-config-client
    prefer-ip-address: true
---
server:
    port: 1112
spring:
    profiles: test
    application:
        name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://192.168.141.1:7002/eureka/
  instance:
    instance-id: microservicecloud-config-client
    prefer-ip-address: true
