spring:
    profiles:
        active:
            - dev
---
server:
    port: 1111
spring:
    profiles: dev
    application:
        name: microservicecloud-config-client
test:
    name: dev
---
server:
    port: 1112
spring:
    profiles: test
    application:
        name: microservicecloud-config-client
test:
    name: test
